services:
  hobby:
    container_name: utils-server
    image: utils-server-image
    networks:
      - utils-server-network
    build: .
    env_file:
      - .env
    ports:
      - "8002:5002"

networks:
  utils-server-network:
    name: utils-server-network