services:
  utility:
    container_name: utils-server
    image: webdevsai/utils-server:latest
    networks:
      - backend
    build: .
    env_file:
      - .env
    ports:
      - "8004:5000"

networks:
  backend:
    external: true