name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Set a timestamp tag as an environment variable
    - name: Set up tag
      id: vars
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    # Step 4: Build the Docker image and tag it
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webdevsai/utils-server:${{ env.TAG }}

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push webdevsai/utils-server:${{ env.TAG }}
